In [ ]:
#Python Library for Data Science - Numpy,Pandas,Matplotlib

In [ ]:
l1 = [4,6,7,2,3]
print(l1)

[4, 6, 7, 2, 3]


In [ ]:
print(l1*2)

[4, 6, 7, 2, 3, 4, 6, 7, 2, 3]


In [ ]:
l2 = []
for val in l1:
  l2.append(val*2)
print(l2)

[8, 12, 14, 4, 6]


In [ ]:
l2 = [[5,8,8,9,4,2] , [5,9,6,3,2,1] , [5,9,8,6,5,4]]
print(l2)

[[5, 8, 8, 9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]]


In [ ]:
#Numpy array
import numpy as np
a = np.array([4,6,7,2,3])
print(a)

[4 6 7 2 3]


In [ ]:
print(a*2)

[ 8 12 14  4  6]


In [ ]:
b = np.array([[5, 8, 8, 9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
c = np.array([[5, 8, 8, 9, 4, 2], [5, 9, 'ABC', 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(c)

[['5' '8' '8' '9' '4' '2']
 ['5' '9' 'ABC' '3' '2' '1']
 ['5' '9' '8' '6' '5' '4']]


In [ ]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
#properties of numpy array : - shape,size,dimensions
print(b.shape)
print(b.size)
print(b.ndim)

(3, 6)
18
2


In [ ]:
#address of any value - array[row index,column index]
print(b[0,1])
print(b[1,4])
print(b[1][4])

8
2
2


In [ ]:
print(b[0])

[5 8 8 9 4 2]


In [ ]:
print(b[1])

[5 9 6 3 2 1]


In [ ]:
print(b[2])

[5 9 8 6 5 4]


In [ ]:
#array[row slicing,column slicing]
print(b[0:1 , 0:3])

[[5 8 8]]


In [ ]:
b = np.array([[5, 8, 8, 9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
#array[initial row index : initial row index+steps , initial col index:intial col index+steps]
print(b[1:3 , 2:5])

[[6 3 2]
 [8 6 5]]


In [ ]:
bs = b[1:3 , 2:5].copy()
bs

array([[6, 3, 2],
       [8, 6, 5]])

In [ ]:
bs[0,1] = 33
print(bs)

[[ 6 33  2]
 [ 8  6  5]]


In [ ]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
d = np.array([[[5,7,6,4] , [7,5,4,2] , [6,8,9,3]] , [[5,9,8,7] , [3,7,3,2] , [5,9,8,5]]])

print(d)

[[[5 7 6 4]
  [7 5 4 2]
  [6 8 9 3]]

 [[5 9 8 7]
  [3 7 3 2]
  [5 9 8 5]]]


In [ ]:
print(d.shape)
print(d.size)
print(d.ndim)

(2, 3, 4)
24
3


In [ ]:
#array[floor index,row index,column index]
print(d[0,2,2])
print(d[1,2,2])

9
8


In [ ]:
b = np.array([[5, 8, 8, 9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
print(np.sum(b))
print(np.prod(b))
print(np.min(b))
print(np.max(b))
print(np.mean(b))
print(np.std(b))
print(np.argmax(b))
print(np.argmin(b))

99
1612431360000
1
9
5.5
2.5
3
11


In [ ]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [ ]:
#for column analysis
print(np.sum(b , axis=0))
print(np.prod(b , axis=0))
print(np.min(b , axis=0))
print(np.max(b , axis=0))
print(np.mean(b , axis=0))
print(np.std(b , axis=0))
print(np.argmax(b , axis=0))
print(np.argmin(b , axis=0))

[15 26 22 18 11  7]
[125 648 384 162  40   8]
[5 8 6 3 2 1]
[5 9 8 9 5 4]
[5.         8.66666667 7.33333333 6.         3.66666667 2.33333333]
[0.         0.47140452 0.94280904 2.44948974 1.24721913 1.24721913]
[0 1 0 0 2 2]
[0 0 1 1 1 1]


In [ ]:
#for row analysis
print(np.sum(b , axis=1))
print(np.prod(b , axis=1))
print(np.min(b , axis=1))
print(np.max(b , axis=1))
print(np.mean(b , axis=1))
print(np.std(b , axis=1))
print(np.argmax(b , axis=1))
print(np.argmin(b , axis=1))

[36 26 37]
[23040  1620 43200]
[2 1 4]
[9 9 9]
[6.         4.33333333 6.16666667]
[2.51661148 2.68741925 1.77169097]
[3 1 1]
[5 5 5]


In [ ]:
b = np.array([[5, 8, 8, -9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(b)

[[ 5  8  8 -9  4  2]
 [ 5  9  6  3  2  1]
 [ 5  9  8  6  5  4]]


In [ ]:
np.sort(b,axis=1)

array([[-9,  2,  4,  5,  8,  8],
       [ 1,  2,  3,  5,  6,  9],
       [ 4,  5,  5,  6,  8,  9]])

In [ ]:
np.sort(b,axis=0)

array([[ 5,  8,  6, -9,  2,  1],
       [ 5,  9,  8,  3,  4,  2],
       [ 5,  9,  8,  6,  5,  4]])

In [ ]:
np.zeros([4,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#array + range
n1 = np.arange(-36,36)
print(n1)

[-36 -35 -34 -33 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19
 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1
   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35]


In [ ]:
n1.reshape(9,8)   #to reshape or change the shape of an array

array([[-36, -35, -34, -33, -32, -31, -30, -29],
       [-28, -27, -26, -25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16, -15, -14, -13],
       [-12, -11, -10,  -9,  -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3],
       [  4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27],
       [ 28,  29,  30,  31,  32,  33,  34,  35]])

In [ ]:
n1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
n2 = np.array([[5,8,9,2],[4,5,3,2]],dtype=complex)
n2

array([[5.+0.j, 8.+0.j, 9.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j, 3.+0.j, 2.+0.j]])

In [ ]:
#Stacking

a = np.array([[6,8,8,3,2],[8,9,4,3,1]])
b = np.array([[4,8,9,4,3]])

In [ ]:
print(a)

[[6 8 8 3 2]
 [8 9 4 3 1]]


In [ ]:
print(b)

[[4 8 9 4 3]]


In [ ]:
#Vertical Stacking
np.vstack((a,b))

array([[6, 8, 8, 3, 2],
       [8, 9, 4, 3, 1],
       [4, 8, 9, 4, 3]])

In [ ]:
c = np.array([[4,5,1],[6,9,6]])
print(c)

[[4 5 1]
 [6 9 6]]


In [ ]:
#Horizontal Stacking
np.hstack((a,c))

array([[6, 8, 8, 3, 2, 4, 5, 1],
       [8, 9, 4, 3, 1, 6, 9, 6]])

In [ ]:
print(a)

[[6 8 8 3 2]
 [8 9 4 3 1]]


In [ ]:
np.transpose(a)

array([[6, 8],
       [8, 9],
       [8, 4],
       [3, 3],
       [2, 1]])

In [ ]:
a.T

array([[6, 8],
       [8, 9],
       [8, 4],
       [3, 3],
       [2, 1]])

In [ ]:
import numpy as np

a = np.array([4, 6, 7, 2, 3])
print(a)

[4 6 7 2 3]


TypeError: ignored

In [ ]:
b = np.array([[1,2,"ABC",4,5],[3,4,5,6,7],[75,45,32,12,11]])
print(b)

[['1' '2' 'ABC' '4' '5']
 ['3' '4' '5' '6' '7']
 ['75' '45' '32' '12' '11']]


In [ ]:
b = np.array([[1,2,"ABC",4,5],[3,4,5,6,7],[75,45,32,12,11]])

b1 = []
b2 = []
for val in b:
  for i in val:
    try:
      #print(int(i))
      b2.append(int(i))
    except:
      #print(ord(i[0]),ord(i[1]),ord(i[2]))
      b2.append(ord(i[0])+ord(i[1])+ord(i[2]))
    b1.append(b2)
    b2 = []

In [ ]:
print(np.array(b1).reshape(3,5))

[[  1   2 198   4   5]
 [  3   4   5   6   7]
 [ 75  45  32  12  11]]
