In [ ]:
#3x + 2y + z = 45
#x + y + 5z = 67
#5x + 5y + 2z = 50

In [ ]:
import numpy as np
a = np.array([[3,5,8],[2,8,6],[1,2,3]])
print(a)

[[3 5 8]
 [2 8 6]
 [1 2 3]]


In [ ]:
b = np.array([[3,2,1]])
print(b)

[[3 2 1]]


In [ ]:
np.dot(a,b.T)

array([[27],
       [28],
       [10]])

In [ ]:
#3x + 2y + z = 45
#x + y + 5z = 67
#5x + 5y + 2z = 50

In [ ]:
A = np.array([[3,2,1],[1,1,5],[5,5,2]])
print(A)

[[3 2 1]
 [1 1 5]
 [5 5 2]]


In [ ]:
X = np.array([['x'],['y'],['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [ ]:
B = np.array([[45],[67],[50]])
print(B)

[[45]
 [67]
 [50]]


In [ ]:
#A.X = B
#X = inv(A).B

A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.         -0.04347826 -0.39130435]
 [-1.         -0.04347826  0.60869565]
 [ 0.          0.2173913  -0.04347826]]


In [ ]:
X = np.dot(A_inv,B)
print(X)

[[ 22.52173913]
 [-17.47826087]
 [ 12.39130435]]


In [ ]:
np.dot(A,X)

array([[45.],
       [67.],
       [50.]])